### PR TITLE
Fix for AssetMatcher to work with Rails 3.2.0

### PR DESCRIPTION
**Pull request by mjtko**
Updated the AssetMatcher logic to work with new Journey routing when operating under Rails 3.2.0.

### CODE REVIEW

**Comment by mjtko** [comment]
Eep, initial version caused 'never reload' behaviour. That caused some brain racking and premature hair loss! Commit cfd4be9 fixes that issue. :)

**Comment by joe1chen** [comment]
@mjtko and @wavii - Quick question - Is rails-dev-tweaks still useful in Rails 3.2.0?

**Comment by mjtko** [comment]
Hi @joe1chen,

I would say that, while rails-dev-tweaks is no longer essential under 3.2.0+, it can still be useful in certain circumstances.

And it's still very useful for people who are stuck on 3.1.x of course.  This patch prevents any accidental breakage when they come to upgrade to 3.2.x (and beyond) which should clearly be avoided!

**Comment by nevir** [comment]
It's still quite useful when you've got gems that haven't optimized themselves for dev-mode performance - rails 3.2 just avoids reloading changed files, but doesn't lock down the entire `to_prepare` process.

**Comment by nevir** [comment]
@mjtko Sorry for the delay on reviewing this, and thanks for the pull request!  I'm digging into it now

**Comment by mjtko** [comment]
@nevir No problem!  Shout if you need any more info. :)

**Comment by nevir** [comment]
Merged in, and released as part of `v0.6.0`

**Pull request closed without merging**
